server:
  port: 8110
  tomcat:
    threads:
      max: 10 #tomcat的最大并发设置为10 默认是200
spring:
  profiles:
    active: dev #环境设置
  application:
    name: service-edu #服务名
  datasource: #mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.50:3306/guli_edu?serverTimezone=GMT%2B8
    username: root
    password: 123456


  #    返回json的全局时间格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.50:8848 #nacos服务地址
    sentinel:
      transport:
        port: 8111 #跟控制台交流的端口
        dashboard: localhost:8888
#        dashboard: 192.168.3.50:8858 #指定控制台服务的地址
#service-oss:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  MaxAutoRetries: 0 #同一实例最大重试次数
  MaxAutoRetriesNextServer: 1 # 其他实例的最大重试次数
  ConnectionTimeout: 5000 # 连接建立的超时时长 默认1s
  ReadTimeout: 5000 # 处理请求的超时时长 默认1s
#mybatis 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/guli/service/edu/mapper/xml/*.xml
#设置日志级别
#logging:
#  level:
#    root: INFO
feign:
  sentinel:
    enabled: true
