server:
  port: 8120

spring:
  profiles:
    active: dev #环境设置
  application:
    name: service-oss #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.50:8848 #nacos服务地址

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI4G4pMF38ZJAmKdWpfCiC
    keySecret: 1LrPrH8gfm3nLKFNAnWyoUbXAhMRUa
    bucketname: guli-file-han